### ISSUE TITLE
tom_nonlocalized events not displaying body of ingested GCN

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_nonlocalizedevents#17]
From Samantha Oats:
"Hi everyone. I have a question about the behaviour of tom_nonlocalized events. With the help of 
[@Griffin Hosseinzadeh](https://tom-toolkit.slack.com/team/UQLKVMT8X)
, I have managed to get it setup to listen to GW events and to report the GCNs for each GW event on the individual GW event pages. However, it seems only to report the title there. I can’t see the body of the GCN. If I click on the right pointing arrow, it turns to a down pointing arrow and a new blank line.  I attach a screenshot just so you can see more clearly what I mean.  Also if I click on the number on the right it takes me to a webpage that looks something like the second screenshot. I don’t know if the two things are related. I can see the GCN message if I go one directory above e.g https://hermes.lco.global/api/v0/messages/   I don’t know if I have set something up incorrectly or am missing something? Thank you Sam

![image](https://github.com/TOMToolkit/tom_nonlocalizedevents/assets/32683393/30357002-6834-4c0a-95b3-86482bf26233)
![image](https://github.com/TOMToolkit/tom_nonlocalizedevents/assets/32683393/e9148afe-1e39-4803-804e-b9eaa1f03cae)

**Comment by jchate6** [comment]
@phycodurus 
This looks like it has a few issues.
I've updated the `README` for the new dev site.

1st, If we can get a UUID, I recommend that `getAlertUrl` on on line 95 of `src.components.AlertsTable.vue` redirects to https://hermes.lco.global/message/UUID instead of to the API since I don't think we have a detail API view for messages.

2nd the message_text isn't being displayed properly.

**Comment by phycodurus** [comment]
The other issue here is not displaying the message content when opening the alert via the left-hand expander triangle. Let's keep this issue open to address that.

**Comment by jchate6** [comment]
Also the changes in that PR that you merged don't actually address the link issue. Those were just some updates I noticed and could easily implement. while researching the issue.

`https://hermes.lco.global/api/v0/messages/61/` => Message Instance 69. This is not the correct message. Also, we have a GUI detail view for a reason, why aren't we redirecting to the frontend here?

**Comment by jnation3406** [comment]
I've fixed the linking to UUID and the message_text not being displayed on click in the above PR

**Comment by jnation3406** [comment]
Fixed in 0.7.7
