### ISSUE TITLE
CWB alerts do not contain distance information

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_nonlocalizedevents#19]
IGWN alerts from the continuous wave burst (CWB) pipeline do not provide distance information in the localization, either in the header (DISTMEAN and DISTSTD) or the skymap table (DISTMU and DISTSIGMA). Right now, this causes `healpix_utils.create_localization_for_skymap` to crash. Can we make these distance attributes optional? Here is an example of a CWB alert for testing: https://gracedb.ligo.org/superevents/S230527ch/view/.

**Comment by jnation3406** [comment]
@griffin-h I can make this change... but an even bigger issue is that this means my introspecting of the gracedb url / filename for the skymap fails for events from the CWB pipeline. This pipeline names the files differently and differs from all the test events I worked with in naming scheme... Do you have any more information about this pipeline and what I can expect, specifically can you have an external_coincidence with this pipeline and if so what is the expected filename for the external_coicidence skymap? Also, do you know of any other pipelines we can expect LIGO events from that I should try to code in there while I'm at it?

**Comment by jnation3406** [comment]
I spoke too soon, I just found an olib pipeline that also names their skymaps olib.fits!

**Comment by jnation3406** [comment]
Also @griffin-h , It is recording the distance attributes because I was initially trying to implement a 3D credible region search. Since then we decided to stick with the 2D search so they aren't really used. Should we remove them, or just ignore them for some pipelines that don't have them? Do they hold any value for you?

**Comment by griffin-h** [comment]
> @griffin-h I can make this change... but an even bigger issue is that this means my introspecting of the gracedb url / filename for the skymap fails for events from the CWB pipeline. This pipeline names the files differently and differs from all the test events I worked with in naming scheme... Do you have any more information about this pipeline and what I can expect, specifically can you have an external_coincidence with this pipeline and if so what is the expected filename for the external_coicidence skymap? Also, do you know of any other pipelines we can expect LIGO events from that I should try to code in there while I'm at it? Browsing around the recent events I see several pipelines (gstlal, MBTA, pyCBC) but so far all of them have the same and consistent skymap naming (bayestar.multiorder.fits) except for CWB...

The full list of options for all the alert parameters (including pipelines) is [here](https://emfollow.docs.ligo.org/userguide/content.html#kafka-notice-gcn-scimma). It doesn't help that much without examples for each pipeline, which I don't think we have. My only advice is what you're already doing; just look through all the (real) [alerts](https://gracedb.ligo.org/superevents/public/O4/) that have come out so far compare the formats. My understanding is that there are only two big categories: compact binary coalescences (CBCs), which have source classifications and distance information, and bursts, which have only durations and frequencies. I think the external coincidence can relate to both, but I have not seen any real alert with an external coincidence yet.

> Also @griffin-h , It is recording the distance attributes because I was initially trying to implement a 3D credible region search. Since then we decided to stick with the 2D search so they aren't really used. Should we remove them, or just ignore them for some pipelines that don't have them? Do they hold any value for you?

I am not currently using the distance, but I do think the 3D credible region is a feature you shouldn't rule out. Our group has talked about using it previously but we haven't switched yet. In general, storing any information they provide seems like a good idea, unless it's a huge amount of extra work.

**Comment by jnation3406** [comment]
Thanks for that list - I had missed it, but it at least bounds the examples I am looking for. I'll implement something to better handle these and ignore distance from the burst types skymaps.

**Comment by jnation3406** [comment]
Fixed in 0.7.7
